### ISSUE TITLE
Doesn't work with webpack 5

### ISSUE THREAD

**Issue by AliaksandrTrubkin** [slutske22/leaflet-vectorhats#37]
When i'm trying to open the map with leaflet-arrowheads
I got this error
![image](https://github.com/slutske22/leaflet-arrowheads/assets/81363332/dd0ac610-6ffa-4c22-87b0-d3c997b6c2af)

Example of my code:

![image](https://github.com/slutske22/leaflet-arrowheads/assets/81363332/b5706d7f-a4d7-4929-b3a3-26270f1dd469)

This code i put inside MapContainer from react-leaflet 4.2.1 version

**Comment by slutske22** [comment]
This is not an issue with this library but rather your code or your build evironment. 

You are importing `leaflet-arrowheads` before you import `leaflet`.  `leaflet-arrowheads` cannot attach all the right logic to `L.Polyline` beacuse as you import it, `L` does not exist yet.  Switch the import order.

[Here is an example codesandbox](https://codesandbox.io/s/react-leaflet-v4-leaflet-arrowheads-srybd6?file=/src/Map.tsx) that is using react 18, react-leaflet 4.2.1, and react-scripts@^5, which uses webpack5 under the hood.

And please, for now and for all future times, don't post screenshots of code, post a codeblock.
