### ISSUE TITLE
update existing arrowhead?

### ISSUE THREAD

**Issue by barchambeault-lightbox** [slutske22/leaflet-vectorhats#43]
i am creating arrowheads with Leaflet.L.polyline() and then attaching arrowheads with .arrowheads().  works great.

but, i am allowing the user to edit a line and like change the color and the style of the arrowhead.  doing this:

const arrowheads = polyline.getArrowheads();
const arrowLayer = arrowheads.getLayers()[0];
arrowLayer.setStyle({ color: xxxx });

works great.  but, it doesn't seem correct.  it seems like there should be a more "correct" way to update the arrowhead style?

also, this doesn't work for like yawn, for example.  passing in yawn to setStyle() does nothing.  my guess is that yawn changes the geometry and therefore setStyle() doesn't cause the recalc of the geometry or something?  So, is there a way to tell an existing arrowhead to change it's geometry?

**Comment by slutske22** [comment]
Without seeing more code, I can't tell you much.  But look into the `perArrowheadOptions` option function as another way to set per-arrowhead options.

The yawn is not part of the `style` of either the polyline or the arrowhead, it gets passed to the `arrowheads()` function itself.  Again, without seeing code, I can't say much.  See if you can make use or the `.redraw` function on the arrowheads layer.  

It sounds like this question is not so much an issue with this plugin but with how to write leaflet code that utilizes it.

**Comment by barchambeault-lightbox** [comment]
Ok, let me try to clarify a little bit.  If I save the layer returned from Leaflet.L.polyline().arrowheads() and later call .setStyle on it, it updates the color/opacity/etc. of the line just fine, but not the arrowhead.  That's why I showed that code I'm using above.  Having to set the style on the line, and then also setting the style on the arrowheads doesn't seem "right" to me, or at least it doesn't seem like I'm doing it correctly.

as far as the yawn, yes, I understand.  the yawn sets the parameters for the geometry of the arrowhead.  but, while i understand that yawn is not something passed into setStyle, calling .arrowheads() again on the layer with a different yawn value doesn't change anything either.  so, again, i must be doing something wrong.

it would probably help if i put together a jsfiddle or codesandbox or something to demonstrate.  i will try to do that.

**Comment by barchambeault-lightbox** [comment]
@slutske22 I did end up figuring this out, and yes, it wasn't this library, but getting the leaflet code correct, and yes, it did involve .redraw().  thanks!
