### ISSUE TITLE
[Question] compatibility with leaflet geoman?

### ISSUE THREAD

**Issue by AndrejGajdos** [slutske22/leaflet-vectorhats#44]
I am trying to use this library with [leaflet-geoman](https://github.com/geoman-io/leaflet-geoman/issues/1398). Leaflet geoman has an option `allowEditing: false` to disable editing for selected layers. It works in general, but for some reason it doesn't work for layers generated by arrowheads. I am not sure if this is good place to ask this question.

[jsfiddle](https://jsfiddle.net/g5c4wfsj/)

```
L.PM.Utils.findLayers(map).forEach((layer) => {
   if (layer?._arrowheads){
  	const arrows = layer.getArrowheads()
        console.log({arrows})
  	arrows?.pm.setOptions({ allowEditing: false })
        arrows?.eachLayer(arrowLayer => {
    	   console.log({arrowLayer})
           arrowLayer?.pm.setOptions({ allowEditing: false })
        })
  }
})
```

<img width="856" alt="Screenshot 2023-09-24 at 10 13 51" src="https://github.com/slutske22/leaflet-arrowheads/assets/1593758/4ab891c4-2371-489b-93c0-7b28a14dcd9c">

**Comment by slutske22** [comment]
This was quite tricky.  The issue is that the arrowheads need to be updated every time the map moves, and we lose the custom options you had set with `.pm.setOptions` every time.  So you have to readd them:

```js
/**
 * Sets options on arrowheads after they were added to map
 */
const setPmOptions = (geoJsonLayer) => geoJsonLayer.eachLayer(layer => {
  // The issue is that this is a new instance of L.layerGroup on every map move - maybe should be fixed in src code
  const arrows = layer.getArrowheads();
  arrows.eachLayer(l => {
    l.pm.setOptions({
      allowEditing: false
    })
  })

})

const parsed = routes.map(route => {
  const geojson = JSON.parse(route.geojsonString);
  const geoJsonLayer = L.geoJSON(geojson, {
    arrowheads: {
      size: '25%',
      frequency: 'endonly',
    },
  })
  geoJsonLayer.addTo(map)
  setPmOptions(geoJsonLayer);
  return geoJsonLayer;
})



map.on('moveend', () => {
  parsed.forEach(geoJsonLayer => {
    setPmOptions(geoJsonLayer)
  })
})
```

## [jsfiddle](https://jsfiddle.net/29w1zaL5/51/)

**Comment by AndrejGajdos** [comment]
@slutske22 thanks!
