### ISSUE TITLE
Arrowhead base at end of line option?

### ISSUE THREAD

**Issue by barchambeault-lightbox** [slutske22/leaflet-vectorhats#45]
Currently, when you do .arrowheads() on the polyline, it draws the tip of the arrowhead at the end of the line, and therefore the base of the arrowhead is actually on the line.  This is not an issue for non-filled arrowheads (it looks better if the line goes to the tip), or filled arrowheads there the opacity is 1 (since the line is obscured by the fully opaque arrowhead).

However, if the opacity is like .5 on a filled arrowhead, the line shows through underneath.  This doesn't look so good.  At least in my opinion.  Is there an option I'm just not seeing to draw the arrowhead so the base is at the end of the line instead of the tip being at the end of the line?

**Comment by slutske22** [comment]
I see what you are saying, but currently there is no option for this kind of offset to achieve your desired result.  It would take some finagling to figure this out, and I don't really have the time to do that ATM.  Feel free to dig in and open a PR.

Closing as this is a use-case specific feature request, that ATM is a `wont-do`, not an issue.
