### ISSUE TITLE
can you add document for _update() method ?? 

### ISSUE THREAD

**Issue by kimsintae** [slutske22/leaflet-vectorhats#49]
Since the arrow style was not being applied immediately to the lineString I created, I used the _update() function. I would appreciate it if you could also include information about the _update() function in the library documentation.

**Comment by slutske22** [comment]
I have 0 context of what you're talking about.  I'm glad you dug in and found the _update() function for whatever your use cae was.  The docs already explain

> Arrowheads inherit all options from [L.Path](https://leafletjs.com/reference-1.6.0.html#path)

So if you reference the leaflet docs, you'll know that the .redraw() method is also available.
