### ISSUE TITLE
Mechanism to keep the z-index of the arrowheads behind other map layers

### ISSUE THREAD

**Issue by timculmer** [slutske22/leaflet-vectorhats#50]
**Problem**

Map layers for the arrowheads are removed then added when they are redrawn, which means they are placed over the top of the existing map layers. Even if the arrowheads were behind a map layer when the polyline was added, zooming or panning the map will cause them to be redrawn over the top of those layers.

**Proposed Solution**

Allow callers to specify a callback that is executed whenever the arrowheads are redrawn. The callback can then reorder the map layers as necessary. For example, if the polyline and arrowheads were always required to be shown underneath the other map layers then following code could be used:

```js
polyline.arrowheads({
    updateCallback: function (polyline) {
        if (polyline._arrowheads) {
            polyline._arrowheads.eachLayer(function (arrowhead) {
                arrowhead.bringToBack();
            });
        }
        polyline.bringToBack();
    }
});
```

Using a callback in this way is a flexible approach which may be useful for other purposes as well.

**Comment by timculmer** [comment]
I have this patch to address this issue. I'm happy to create a Pull Request for it:
```patch
diff --git "a/libs/leaflet-arrowheads/1.4.0/leaflet-arrowheads.js" "b/libs/leaflet-arrowheads/1.4.0/leaflet-arrowheads.js"
index bbb2600..a40c4b7 100644
--- "a/libs/leaflet-arrowheads/1.4.0/leaflet-arrowheads.js"
+++ "b/libs/leaflet-arrowheads/1.4.0/leaflet-arrowheads.js"
@@ -75,6 +75,7 @@ L.Polyline.include({
 			size: '15%',
 			frequency: 'allvertices',
 			proportionalToTotal: false,
+			updateCallback: undefined
 		};
 
 		this.options.noClip = true;
@@ -484,6 +485,11 @@ L.Polyline.include({
 		if (this._hatsApplied) {
 			this.buildVectorHats(this._arrowheadOptions);
 			this._map.addLayer(this._arrowheads);
+
+			// Call the update callback if one was specified in the options
+			if (this._arrowheadOptions.updateCallback !== undefined) {
+				this._arrowheadOptions.updateCallback(this);
+			}
 		}
 	},
```

**Comment by timculmer** [comment]
I just discovered [Panes](https://leafletjs.com/examples/map-panes/) in Leaflet which allow you to control the z-index of a map layer. Using them is a much better solution for setting the z-index of the arrowhead polylines than my proposed solution. Therefore I will close this issue.

Example of how to use panes with arrowheads:

```js
let map = L.map('map');
map.createPane('myPane');
map.getPane('myPane').style.zIndex = 650;
let myVector = L.polyline(
    [coords], {
        pane: 'myPane'
    }
).arrowheads();
myVector.addTo(map);
```

**Comment by slutske22** [comment]
Hey Tim, thanks for the discussion.  Yes, this is the perfect use case for `panes`.  Thanks for using the library!
